name: build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

env:
  MAKEFLAGS: j3
  # set some variables for Visual Studio
  MultiProcessorCompilation: true
  UseMultiToolTask: true
  EnforceProcessCountAcrossBuilds: true

jobs:
  build:
    name: build-windows-latest
    runs-on: windows-latest
    steps:
    - name: "Check out source"
      uses: actions/checkout@v2
    - name: Configure build for amd64
      uses: ilammy/msvc-dev-cmd@v1
      with:
          arch: amd64
    - name: "Install dependencies"
      run: python -m pip install -r requirements.txt
    - name: "Build"
      run: python -m qsc manifest.yml
    - name: "List"
      run: ls
    - name: "List"
      run: ls dist
    - name: "Upload distribution artifact"
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
